# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-06 16:19
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=10, verbose_name='姓名')),
                ('sex', models.CharField(choices=[('M', '男'), ('F', '女'), ('U', '未选择')], default='U', max_length=1, verbose_name='性别')),
                ('identity', models.CharField(blank=True, max_length=50, verbose_name='身份')),
                ('college', models.CharField(blank=True, max_length=50, verbose_name='学院')),
                ('major', models.CharField(blank=True, max_length=50, verbose_name='专业')),
                ('avatar', models.ImageField(blank=True, upload_to='users/avatars', verbose_name='头像')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '个人档案',
                'verbose_name': '个人档案',
            },
        ),
    ]
