# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-17 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[('U', '未选择'), ('M', '男'), ('F', '女')], default='U', max_length=1, verbose_name='性别'),
        ),
    ]
