# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-23 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171017_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[('U', '未选择'), ('F', '女'), ('M', '男')], default='U', max_length=1, verbose_name='性别'),
        ),
    ]
