version: '3'

services:
  db:
    image: postgres:9.6
  web:
    build: .
    name: csthome_web
    volumes:
      - .:/src
    depends_on:
      - db
  proxy:
    image: nginx:1.13
    ports:
      - "12138:80"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - .:/src
    depends_on:
      - web
