version: '3'

services:
  proxy:
    image: nginx:1.13
    ports:
      - "12138:80"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - .:/src
    depends_on:
      - web
  web:
    build: .
    volumes:
      - .:/src