version: '2'

volumes:
  postgres_data:
  postgres_backup:
  django_static:
  django_media:

services:

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
    env_file:
      - ./.envs/.production/.postgres

  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    depends_on:
      - postgres
    volumes:
      - django_static:/app/static
      - django_media:/app/csthome/media
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /gunicorn.sh

  proxy:
    image: nginx:1.13
    ports:
      - "12138:80"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - django_static:/app/static
      - django_media:/app/media
    depends_on:
      - django
