# Generated by Django 2.0.2 on 2018-03-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PushNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=100, verbose_name='内容')),
                ('has_pushed', models.BooleanField(default=False, editable=False, verbose_name='是否已推送')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '推送通知',
                'verbose_name_plural': '推送通知',
            },
        ),
    ]
