# Generated by Django 2.0.2 on 2018-03-21 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[('U', '未选择'), ('M', '男'), ('F', '女')], default='U', max_length=1, verbose_name='性别'),
        ),
    ]
