# Generated by Django 2.0.2 on 2018-03-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180321_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[('M', '男'), ('F', '女'), ('U', '未选择')], default='U', max_length=1, verbose_name='性别'),
        ),
    ]
