# Generated by Django 2.0.2 on 2018-03-24 12:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180321_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='application_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='申请入党时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='join_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='入党时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='organization',
            field=models.CharField(blank=True, max_length=50, verbose_name='党支部'),
        ),
    ]
