# Generated by Django 2.0.2 on 2018-03-24 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180324_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='application_date',
            field=models.DateField(blank=True, null=True, verbose_name='申请入党时间'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='join_date',
            field=models.DateField(blank=True, null=True, verbose_name='入党时间'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
