# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-01 09:16
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('photo', models.ImageField(blank=True, upload_to='event', verbose_name='照片')),
                ('body', ckeditor.fields.RichTextField(verbose_name='正文')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_headline', models.BooleanField(default=False, verbose_name='是否需要首页轮播')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否需要签到')),
                ('attendees', models.ManyToManyField(blank=True, editable=False, to=settings.AUTH_USER_MODEL, verbose_name='参与者')),
            ],
            options={
                'verbose_name': '活动',
                'verbose_name_plural': '活动',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('photo', models.ImageField(blank=True, upload_to='news', verbose_name='照片')),
                ('body', ckeditor.fields.RichTextField(verbose_name='正文')),
                ('created', models.DateField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '新闻',
                'verbose_name_plural': '新闻',
            },
        ),
    ]
