# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-17 10:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('created',), 'verbose_name': '活动', 'verbose_name_plural': '活动'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('created',), 'verbose_name': '新闻', 'verbose_name_plural': '新闻'},
        ),
    ]
