# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-01 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushnotification',
            name='has_pushed',
            field=models.BooleanField(default=False, editable=False, verbose_name='是否已推送'),
        ),
    ]
