# Generated by Django 2.0.2 on 2018-03-21 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='some_field',
        ),
    ]
