# Generated by Django 2.0.2 on 2018-03-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180325_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('source', models.CharField(max_length=50, verbose_name='来源')),
                ('body', models.TextField(verbose_name='正文')),
                ('created', models.DateField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '党课记录',
                'verbose_name_plural': '党课记录',
                'ordering': ('-created',),
            },
        ),
    ]
