swagger: '2.0'

info:
  version: 1.0.0
  title: CST Home

tags:
  - name: home
    description: 获取活动以及新闻。
  - name: users
    description: 用户登录、注册、修改密码以及编辑个人资料。

schemes:
  - http

paths:
  /home/events/:
    get:
      tags:
        - homeø
      summary: 获取所有活动
      description: 添加headline=true查询参数以获取所有轮播区的活动；添加active=true以添加所有需要签到的活动。
      parameters:
        - name: active
          in: query
          description: 是否需要签到
          required: false
          type: string
        - name: headline
          in: query
          description: 是否需要轮播
          required: false
          type: string
      responses:
        200:
          description: OK

  /home/events/{event_id}/:
    get:
      tags:
        - home
      summary: 获取单个活动
      description: 根据ID获取单个活动的详细内容。
      parameters:
        - name: event_id
          in: path
          description: 所需获取活动的ID
          required: true
          type: integer
      responses:
        200:
          description: OK
        404:
          description: 未找到所需的活动

  /home/news/:
    get:
      tags:
        - home
      summary: 获取所有新闻（分页）
      description: 第一次访问此端点，可获得数量等于页数的新闻实例。如果需要浏览下一页的新闻，只需根据返回的next字段给的URL访问即可。
      responses:
        200:
          description: OK

  /home/news/{news_id}:
    get:
      tags:
        - home
      summary: 获取单条新闻
      description: 根据ID获取单条新闻的详细内容。
      parameters:
        - name: news_id
          in: path
          description: 所需获取新闻的ID
          required: true
          type: integer
      responses:
        200:
          description: OK
        404:
          description: 未找到所需的新闻

  /users/login/:
    post:
      tags:
        - users
      summary: 用户登录
      parameters:
        - name: data
          in: body
          description: 用户登录表单
          required: true
          schema:
            $ref: "#/definitions/User"
      responses:
        200:
          description: 登陆成功
        400:
          description: 用户名或密码错误

  /users/change-password/:
    put:
      tags:
        - users
      summary: 用户修改密码
      description: 请先login以验证旧密码是否正确后，再访问此端点修改密码。
      parameters:
        - name: Authorization
          in: header
          type: string
          description: 密钥，格式为"Token xxxxxxx"
          required: true
        - name: data
          in: body
          description: 用户修改密码的表单
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        200:
          description: 修改成功
        400:
          description: 用户名有误

  /users/profile/:
    get:
      tags:
        - users
      summary: 获取用户资料
      parameters:
        - name: Authorization
          in: header
          type: string
          description: 密钥，格式为"Token xxxxxxx"
          required: true
      responses:
        200:
          description: 成功获取
        401:
          description: 未提供有效的认证密钥
    put:
      tags:
        - users
      summary: 更新用户资料
      consumes:
        - multipart/form-data
      produces:
        - application/json
      parameters:
        - name: Authorization
          in: header
          type: string
          description: 密钥，格式为"Token xxxxxxx"
          required: true
        - name: full_name
          in: formData
          type: string
          description: 姓名
        - name: sex
          in: formData
          type: string
          description: 性别。'M'表示男, 'F'表示女, 'U'表示未选择
        - name: identity
          in: formData
          type: string
          description: 身份（'共青团员','共产党员', '群众'）
        - name: college
          in: formData
          type: string
          description: 所在学院
        - name: major
          in: formData
          type: string
          description: 所在专业
        - name: avatar
          in: formData
          type: file
          description: 头像
      responses:
        200:
          description: 更新成功

definitions:
  User:
    type: object
    required:
      - username
      - password
    properties:
      username:
        type: string
      password:
        type: string
